<h1>Commit details for <?php echo $this->hash; ?></h1>

<?php
	$repo = $this->repository;

	if (isset($this->details['parent'])) {
		$hash = $this->details['parent'];
		echo "<a href=\"/commit/repository/$repo/hash/$hash/\">Parent commit</a> -- ";
	} elseif (isset($this->details['parents'])) {
		echo "Parent commits: ";
		foreach ($this->details['parents'] as $i => $parent) {
			$n = $i+1;
			echo "<a href=\"/commit/repository/$repo/hash/$parent/\">$n</a> ";
		}
		echo ' --';
	}

	$treeUrl = "/tree/repository/$repo/from/" . $this->details['tree'];
?>

<a href="<?php echo $treeUrl; ?>">Tree</a>

<br /><br />
<?php echo $this->details['message']; ?>
<br /><br />

<h3>Author</h3>
<?php echo getPerson($this->details, 'author'); ?>

<?php
	if ($this->details['author'] !== $this->details['committer']) {
		echo "<h3>Committer</h3>";
		echo getPerson($this->details, 'committer');
	}
?>

<?php

	function getPerson($details, $kind)
	{
		$html  = $details[$kind]['name'] . " <{$details[$kind]['email']}><br />";
		$html .= "on " . date('d-m-y H:i', $details[$kind]['timestamp']);

		return $html;
	}

?>