<h1>Commit details for <?php echo $this->hash; ?></h1>

<?php
	$repo = $this->repository;

	if ($this->details['parent'] !== null) {
		$hash = $this->details['parent'];
		echo "<a href=\"/commit/repository/$repo/hash/$hash/\">Parent commit</a> -- ";
	}

	$treeUrl = "/tree/repository/$repo/from/" . $this->details['tree'];
?>

<a href="<?php echo $treeUrl; ?>">Tree</a>

<br /><br />

<h3>Author</h3>
<?php echo getPerson($this->details, 'author'); ?>

<?php
	if ($this->details['author'] !== $this->details['committer']) {
		echo "<h3>Committer</h3>";
		echo getPerson('author');
	}
?>

<?php

	function getPerson($details, $kind)
	{
		$html  = $details['author']['name'] . " <{$details['author']['email']}><br />";
		$html .= "on " . date('d-m-y H:i', $details['author']['timestamp']);

		return $html;
	}

?>