<?php

$logs = array();

	foreach ($this->logs as $entry) {
		$info = $entry->getInfo();

		$logs[] = $info;

//		$url = "/commit/repository/{$this->name}/hash/{$info['hash']}";
//		$hash = "<a href='$url'>" . $info['hash'] . '</a>';
//		$author = $info['author']['name'];
//			//@todo: provide also email
//			//@todo: if committer is different, notice this
//		$date = date("d-m-y H:i", $info['author']['timestamp']);
//		echo "Commit: $hash -- by $author on $date<br/>";
	}

echo json_encode(array(
	'success' => true,
	'commits' => $logs
));