<h1><?php echo $this->name; ?></h1>

<?php
	if ($this->hasDefaultDescription) {
		$description = _('This repository has the default description. Click here to discover how to change it.');
	} else {
		$description = $this->description;
	}
?>

<p><?php echo $description; ?></p>

<h3>Logs</h3>
<?php
	foreach ($this->logs as $entry) {

	}
?>

<h3>Branches</h3>
<?php
	foreach ($this->branches as $branch) {

	}
?>

