<h1><?php echo $this->name; ?> - on branch <?php echo $this->branch; ?></h1>

<?php
	if ($this->hasDefaultDescription) {
		$description = _('This repository has the default description. Set it in <code>.git/description</code> file.');
	} else {
		$description = $this->description;
	}
?>

<p><?php echo $description; ?></p>

<h3>Logs</h3>
<?php
	foreach ($this->logs as $entry) {
		$info = $entry->getInfo();
		$url = "/commit/repository/{$this->name}/hash/{$info['hash']}";
		$hash = "<a href='$url'>" . $info['hash'] . '</a>';
		$author = $info['author']['name'];
			//@todo: provide also email
			//@todo: if committer is different, notice this
		$date = date("d-m-y H:i", $info['author']['timestamp']);
		echo "Commit: $hash -- by $author on $date<br/>";
	}
?>

<h3>Branches</h3>
<?php
	foreach ($this->branches as $branch) {
		$url = '/repository' . $this->getUrl(array('branch' => $branch['name']));
		$detail = '<em>' . $branch['message'] . '</em> -- on ' . $branch['hash'];
		echo "<a href='$url'>{$branch['name']}</a> - $detail";
	}
?>

