<?php
	if ($this->hasDefaultDescription) {
		$description = _('This repository has the default description. Set it in <code>.git/description</code> file.');
	} else {
		$description = $this->description;
	}
?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->name; ?></title>

    <link rel="stylesheet" type="text/css" href="/client/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="http://dev.sencha.com/deploy/dev/examples/layout-browser/layout-browser.css" />
    <script type="text/javascript" src="/client/adapter/ext/ext-base.js"></script>
    <script type="text/javascript" src="/client/ext-all-debug.js"></script>
    <script type="text/javascript" src="/client/branchlist.js"></script>
    <script type="text/javascript" src="/client/commitsgrid.js"></script>
    <script type="text/javascript" src="/client/branchpanel.js"></script>
    <script type="text/javascript" src="/client/detailpanel.js"></script>
    <script type="text/javascript" src="/client/viewport.js"></script>
</head>
<body>

<script type="text/javascript">
Ext.onReady(function(){
    new Gittorama.Viewport({
		repositoryName: '<?php echo $this->name; ?>',
		repositoryDescription: <?php echo json_encode($description); ?>
    });
});
</script>
<div id="header"><h1><?php echo $this->name; ?></h1></div>
</body>
</html>
